Repository voxpupuli/puppet-mcollective, pull requests merged in 2018-07, with the labels that each got.

#369 Quieten coerce warning
  manifests/common/config/connector/activemq/hosts_iteration.pp
Labels: bug

#370 modulesync 1.9.3
  .msync.yml
  Gemfile
Labels: modulesync

#371 release 3.1.1
  CHANGELOG.md
  metadata.json
Labels: skip-changelog

#372 modulesync 1.9.3
  .msync.yml
Labels: modulesync

#373 modulesync 1.9.4
  .msync.yml
  .travis.yml
Labels: modulesync
